### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by 400lbhacker** [pengbo-learn/python-color-transfer#1]
AttributeError: 'NoneType' object has no attribute 'shape'
cannot get to work in google colab

**Comment by pengbo-learn** [comment]
> AttributeError: 'NoneType' object has no attribute 'shape' cannot get to work in google colab

```git clone``` seems failing at download images correctly. You could download these test images by hand and run again.
